# Configuration for dev profile
spring:
  config:
    activate:
      on-profile: dev
app:
  external:
    maintenance-service-url: ${MS_MAINTENANCE_SERVICE_PORT:http://localhost:9090}
# Configuration for prod profile
---
spring:
  config:
    activate:
      on-profile: prod
app:
  external:
    maintenance-service-url: ${MS_MAINTENANCE_SERVICE_PORT}