spring.application.name=appmic-e-commerceplugins-gateway
server.port=80
spring.cloud.gateway.mvc.routes[0].id=appmic-e-commerceplugins-maintenance
spring.cloud.gateway.mvc.routes[0].uri=${LB_MAINTENANCE_SERVICE:http://127.0.0.1:9090}
spring.cloud.gateway.mvc.routes[0].predicates=Path=/api/maintenance/**

spring.cloud.gateway.mvc.routes[1].id=appmic-e-commerceplugins-orders
spring.cloud.gateway.mvc.routes[1].uri=${LB_ORDER_SERVICE:http://127.0.0.1:9091}
spring.cloud.gateway.mvc.routes[1].predicates=Path=/api/orders/**

spring.cloud.gateway.mvc.routes[2].id=appmic-e-commerceplugins-auth
spring.cloud.gateway.mvc.routes[2].uri=${LB_AUTH_SERVICE:http://127.0.0.1:9000}
spring.cloud.gateway.mvc.routes[2].predicates=Path=/api/auth/**

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

#Configuration for dev environment
spring.config.activate.on-profile=dev