# ===============================================
# SECCIÓN PRINCIPAL (COMÚN A TODOS LOS PERFILES)
# ===============================================
server:
  port: 9000
spring:
  application:
    name: appmic-e-commerceplugins-auth
  security:
    oauth2:
      client:
        registration:
          # Este nombre debe ser único y lo usaremos en la configuración del WebClient
          maintenance-client-credentials:
            provider: spring # El nombre del provider que definiremos a continuación
            client-id: maintenance-client
            client-secret: 12345
            authorization-grant-type: client_credentials
            scope: internal.write # El permiso que vamos a solicitar
        provider:
          spring:
            # La URL base de tu propio servidor de autorización
            token-uri: ${LB_AUTH_SERVICE:http://127.0.0.1:9000}/oauth2/token
  # La clave para que funcione en local y en Kubernetes
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
app:
  external:
    # Se define la variable, pero el valor se asigna en el perfil correspondiente
    maintenance-service-url: ${MS_MAINTENANCE}
  frontend:
    # Toma la variable FRONTEND_URL, si no existe, usa localhost
    url: ${FRONTEND_URL:http://localhost:4200}
  endpoints:
    auth: "/api/auth"

# ===============================================
# SEPARADOR DE PERFIL
# ===============================================
---
# ===============================================
# PROPIEDADES EXCLUSIVAS PARA EL PERFIL 'dev'
# ===============================================
spring:
  config:
    activate:
      on-profile: dev

app:
  external:
    # Valor por defecto para la URL en el entorno de desarrollo
    maintenance-service-url: ${MS_MAINTENANCE:http://127.0.0.1:9090}
  frontend:
    # Toma la variable FRONTEND_URL, si no existe, usa localhost
    url: ${FRONTEND_URL:http://localhost:4200}
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
          oauth2:
            server:
              authorization:
                web: DEBUG
                authentication: DEBUG
                client: DEBUG
                token: DEBUG
                OAuth2AuthorizationService: DEBUG
