spring.application.name=appmic-e-commerceplugins-auth
server.port=9001
#SPRING SECURITY
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization.web=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization.authentication=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization.client=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization.token=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization.OAuth2AuthorizationService=DEBUG